# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "say_bye": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://deven367.github.io/new_nb/"

git_url = "https://github.com/deven367/new_nb/tree/master/"

def custom_doc_links(name): return None
