# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'say_bye']

# Cell
def say_hello(name):
    return f'Hello {name}!'

# Cell
def say_bye(name):
    return f'Bye {name}!'